name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: labs7/go-sample:${{ github.run_id }}
      - name: Checkout labs7/go-sample-deploy repo
        uses: actions/checkout@v2
        with:
          repository: labs7/go-sample-deploy
      - name: Create local changes
      run: |
        sed 's/^appVersion.*/appVersion: '"${{ github.run_id }}"'/g' go-sample/Chart.yaml 
      - name: Commit change
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "update AppVersion" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: labs7/go-sample-deploy